//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroMarketRD.Playground.AgroMarketWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAgroContract", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgroMarketRD.Playground.AgroMarketWS.ProductResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgroMarketRD.Playground.AgroMarketWS.ProductUnitResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgroMarketRD.Playground.AgroMarketWS.GeneralResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgroMarketRD.Playground.AgroMarketWS.OfferResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgroMarketRD.Playground.AgroMarketWS.RequestResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgroMarketRD.Playground.AgroMarketWS.LoginResponse))]
    public partial class BaseAgroContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AgroMarketRD.Playground.AgroMarketWS.ErrorResponse ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgroMarketRD.Playground.AgroMarketWS.ErrorResponse Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class ErrorResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProductResponse : AgroMarketRD.Playground.AgroMarketWS.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AgroMarketRD.Playground.AgroMarketWS.Product[] ProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgroMarketRD.Playground.AgroMarketWS.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductUnitResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProductUnitResponse : AgroMarketRD.Playground.AgroMarketWS.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AgroMarketRD.Playground.AgroMarketWS.ProductUnit[] UnitTypesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgroMarketRD.Playground.AgroMarketWS.ProductUnit[] UnitTypes {
            get {
                return this.UnitTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitTypesField, value) != true)) {
                    this.UnitTypesField = value;
                    this.RaisePropertyChanged("UnitTypes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class GeneralResponse : AgroMarketRD.Playground.AgroMarketWS.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfferResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class OfferResponse : AgroMarketRD.Playground.AgroMarketWS.BaseAgroContract {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class RequestResponse : AgroMarketRD.Playground.AgroMarketWS.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AgroMarketRD.Playground.AgroMarketWS.Request[] RequestsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgroMarketRD.Playground.AgroMarketWS.Request[] Requests {
            get {
                return this.RequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestsField, value) != true)) {
                    this.RequestsField = value;
                    this.RaisePropertyChanged("Requests");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntentionBuyingResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class IntentionBuyingResponse : AgroMarketRD.Playground.AgroMarketWS.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AgroMarketRD.Playground.AgroMarketWS.IntentionBuying[] IntentionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgroMarketRD.Playground.AgroMarketWS.IntentionBuying[] Intentions {
            get {
                return this.IntentionsField;
            }
            set {
                if ((object.ReferenceEquals(this.IntentionsField, value) != true)) {
                    this.IntentionsField = value;
                    this.RaisePropertyChanged("Intentions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : AgroMarketRD.Playground.AgroMarketWS.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductUnit", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProductUnit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuyerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductUnitIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuyerId {
            get {
                return this.BuyerIdField;
            }
            set {
                if ((this.BuyerIdField.Equals(value) != true)) {
                    this.BuyerIdField = value;
                    this.RaisePropertyChanged("BuyerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductUnitId {
            get {
                return this.ProductUnitIdField;
            }
            set {
                if ((this.ProductUnitIdField.Equals(value) != true)) {
                    this.ProductUnitIdField = value;
                    this.RaisePropertyChanged("ProductUnitId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntentionBuying", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class IntentionBuying : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OfferIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfferId {
            get {
                return this.OfferIdField;
            }
            set {
                if ((this.OfferIdField.Equals(value) != true)) {
                    this.OfferIdField = value;
                    this.RaisePropertyChanged("OfferId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgroMarketWS.IAgroMarketService")]
    public interface IAgroMarketService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/SignIn", ReplyAction="http://tempuri.org/IAgroMarketService/SignInResponse")]
        AgroMarketRD.Playground.AgroMarketWS.LoginResponse SignIn(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/SignIn", ReplyAction="http://tempuri.org/IAgroMarketService/SignInResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.LoginResponse> SignInAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetProducts", ReplyAction="http://tempuri.org/IAgroMarketService/GetProductsResponse")]
        AgroMarketRD.Playground.AgroMarketWS.ProductResponse GetProducts(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetProducts", ReplyAction="http://tempuri.org/IAgroMarketService/GetProductsResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.ProductResponse> GetProductsAsync(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetUnitTypes", ReplyAction="http://tempuri.org/IAgroMarketService/GetUnitTypesResponse")]
        AgroMarketRD.Playground.AgroMarketWS.ProductUnitResponse GetUnitTypes(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetUnitTypes", ReplyAction="http://tempuri.org/IAgroMarketService/GetUnitTypesResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.ProductUnitResponse> GetUnitTypesAsync(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateOffer", ReplyAction="http://tempuri.org/IAgroMarketService/CreateOfferResponse")]
        AgroMarketRD.Playground.AgroMarketWS.GeneralResponse CreateOffer(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateOffer", ReplyAction="http://tempuri.org/IAgroMarketService/CreateOfferResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.GeneralResponse> CreateOfferAsync(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/RemoveOffer", ReplyAction="http://tempuri.org/IAgroMarketService/RemoveOfferResponse")]
        AgroMarketRD.Playground.AgroMarketWS.ErrorResponse RemoveOffer(string userId, string token, int offerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/RemoveOffer", ReplyAction="http://tempuri.org/IAgroMarketService/RemoveOfferResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.ErrorResponse> RemoveOfferAsync(string userId, string token, int offerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetOffer", ReplyAction="http://tempuri.org/IAgroMarketService/GetOfferResponse")]
        AgroMarketRD.Playground.AgroMarketWS.OfferResponse GetOffer(string userId, string token, int offerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetOffer", ReplyAction="http://tempuri.org/IAgroMarketService/GetOfferResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.OfferResponse> GetOfferAsync(string userId, string token, int offerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetOffersProductor", ReplyAction="http://tempuri.org/IAgroMarketService/GetOffersProductorResponse")]
        AgroMarketRD.Playground.AgroMarketWS.OfferResponse GetOffersProductor(string userId, string token, int productorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetOffersProductor", ReplyAction="http://tempuri.org/IAgroMarketService/GetOffersProductorResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.OfferResponse> GetOffersProductorAsync(string userId, string token, int productorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllOffers", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllOffersResponse")]
        AgroMarketRD.Playground.AgroMarketWS.OfferResponse GetAllOffers(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllOffers", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllOffersResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.OfferResponse> GetAllOffersAsync(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateRequest", ReplyAction="http://tempuri.org/IAgroMarketService/CreateRequestResponse")]
        AgroMarketRD.Playground.AgroMarketWS.GeneralResponse CreateRequest(string userId, string token, int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateRequest", ReplyAction="http://tempuri.org/IAgroMarketService/CreateRequestResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.GeneralResponse> CreateRequestAsync(string userId, string token, int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/RemoveRequest", ReplyAction="http://tempuri.org/IAgroMarketService/RemoveRequestResponse")]
        AgroMarketRD.Playground.AgroMarketWS.ErrorResponse RemoveRequest(string userId, string token, int requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/RemoveRequest", ReplyAction="http://tempuri.org/IAgroMarketService/RemoveRequestResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.ErrorResponse> RemoveRequestAsync(string userId, string token, int requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetRequest", ReplyAction="http://tempuri.org/IAgroMarketService/GetRequestResponse")]
        AgroMarketRD.Playground.AgroMarketWS.RequestResponse GetRequest(string userId, string token, int requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetRequest", ReplyAction="http://tempuri.org/IAgroMarketService/GetRequestResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.RequestResponse> GetRequestAsync(string userId, string token, int requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetRequestsBuyer", ReplyAction="http://tempuri.org/IAgroMarketService/GetRequestsBuyerResponse")]
        AgroMarketRD.Playground.AgroMarketWS.RequestResponse GetRequestsBuyer(string userId, string token, int buyerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetRequestsBuyer", ReplyAction="http://tempuri.org/IAgroMarketService/GetRequestsBuyerResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.RequestResponse> GetRequestsBuyerAsync(string userId, string token, int buyerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllRequests", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllRequestsResponse")]
        AgroMarketRD.Playground.AgroMarketWS.RequestResponse GetAllRequests(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllRequests", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllRequestsResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.RequestResponse> GetAllRequestsAsync(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetIntentionBuying", ReplyAction="http://tempuri.org/IAgroMarketService/GetIntentionBuyingResponse")]
        AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse GetIntentionBuying(string userId, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetIntentionBuying", ReplyAction="http://tempuri.org/IAgroMarketService/GetIntentionBuyingResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse> GetIntentionBuyingAsync(string userId, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CancelIntentionBuying", ReplyAction="http://tempuri.org/IAgroMarketService/CancelIntentionBuyingResponse")]
        AgroMarketRD.Playground.AgroMarketWS.ErrorResponse CancelIntentionBuying(string userId, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CancelIntentionBuying", ReplyAction="http://tempuri.org/IAgroMarketService/CancelIntentionBuyingResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.ErrorResponse> CancelIntentionBuyingAsync(string userId, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllIntentionsBuying", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllIntentionsBuyingResponse")]
        AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse GetAllIntentionsBuying(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllIntentionsBuying", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllIntentionsBuyingResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse> GetAllIntentionsBuyingAsync(string userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/MakeDeal", ReplyAction="http://tempuri.org/IAgroMarketService/MakeDealResponse")]
        AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse MakeDeal(string userId, string token, int offerId, int requestId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/MakeDeal", ReplyAction="http://tempuri.org/IAgroMarketService/MakeDealResponse")]
        System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse> MakeDealAsync(string userId, string token, int offerId, int requestId, int quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgroMarketServiceChannel : AgroMarketRD.Playground.AgroMarketWS.IAgroMarketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgroMarketServiceClient : System.ServiceModel.ClientBase<AgroMarketRD.Playground.AgroMarketWS.IAgroMarketService>, AgroMarketRD.Playground.AgroMarketWS.IAgroMarketService {
        
        public AgroMarketServiceClient() {
        }
        
        public AgroMarketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgroMarketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgroMarketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgroMarketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.LoginResponse SignIn(string userName, string password) {
            return base.Channel.SignIn(userName, password);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.LoginResponse> SignInAsync(string userName, string password) {
            return base.Channel.SignInAsync(userName, password);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.ProductResponse GetProducts(string userId, string token) {
            return base.Channel.GetProducts(userId, token);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.ProductResponse> GetProductsAsync(string userId, string token) {
            return base.Channel.GetProductsAsync(userId, token);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.ProductUnitResponse GetUnitTypes(string userId, string token) {
            return base.Channel.GetUnitTypes(userId, token);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.ProductUnitResponse> GetUnitTypesAsync(string userId, string token) {
            return base.Channel.GetUnitTypesAsync(userId, token);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.GeneralResponse CreateOffer(string userId, string token) {
            return base.Channel.CreateOffer(userId, token);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.GeneralResponse> CreateOfferAsync(string userId, string token) {
            return base.Channel.CreateOfferAsync(userId, token);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.ErrorResponse RemoveOffer(string userId, string token, int offerId) {
            return base.Channel.RemoveOffer(userId, token, offerId);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.ErrorResponse> RemoveOfferAsync(string userId, string token, int offerId) {
            return base.Channel.RemoveOfferAsync(userId, token, offerId);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.OfferResponse GetOffer(string userId, string token, int offerId) {
            return base.Channel.GetOffer(userId, token, offerId);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.OfferResponse> GetOfferAsync(string userId, string token, int offerId) {
            return base.Channel.GetOfferAsync(userId, token, offerId);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.OfferResponse GetOffersProductor(string userId, string token, int productorId) {
            return base.Channel.GetOffersProductor(userId, token, productorId);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.OfferResponse> GetOffersProductorAsync(string userId, string token, int productorId) {
            return base.Channel.GetOffersProductorAsync(userId, token, productorId);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.OfferResponse GetAllOffers(string userId, string token) {
            return base.Channel.GetAllOffers(userId, token);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.OfferResponse> GetAllOffersAsync(string userId, string token) {
            return base.Channel.GetAllOffersAsync(userId, token);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.GeneralResponse CreateRequest(string userId, string token, int productId, int quantity) {
            return base.Channel.CreateRequest(userId, token, productId, quantity);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.GeneralResponse> CreateRequestAsync(string userId, string token, int productId, int quantity) {
            return base.Channel.CreateRequestAsync(userId, token, productId, quantity);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.ErrorResponse RemoveRequest(string userId, string token, int requestId) {
            return base.Channel.RemoveRequest(userId, token, requestId);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.ErrorResponse> RemoveRequestAsync(string userId, string token, int requestId) {
            return base.Channel.RemoveRequestAsync(userId, token, requestId);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.RequestResponse GetRequest(string userId, string token, int requestId) {
            return base.Channel.GetRequest(userId, token, requestId);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.RequestResponse> GetRequestAsync(string userId, string token, int requestId) {
            return base.Channel.GetRequestAsync(userId, token, requestId);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.RequestResponse GetRequestsBuyer(string userId, string token, int buyerId) {
            return base.Channel.GetRequestsBuyer(userId, token, buyerId);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.RequestResponse> GetRequestsBuyerAsync(string userId, string token, int buyerId) {
            return base.Channel.GetRequestsBuyerAsync(userId, token, buyerId);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.RequestResponse GetAllRequests(string userId, string token) {
            return base.Channel.GetAllRequests(userId, token);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.RequestResponse> GetAllRequestsAsync(string userId, string token) {
            return base.Channel.GetAllRequestsAsync(userId, token);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse GetIntentionBuying(string userId, string token, int intentionId) {
            return base.Channel.GetIntentionBuying(userId, token, intentionId);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse> GetIntentionBuyingAsync(string userId, string token, int intentionId) {
            return base.Channel.GetIntentionBuyingAsync(userId, token, intentionId);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.ErrorResponse CancelIntentionBuying(string userId, string token, int intentionId) {
            return base.Channel.CancelIntentionBuying(userId, token, intentionId);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.ErrorResponse> CancelIntentionBuyingAsync(string userId, string token, int intentionId) {
            return base.Channel.CancelIntentionBuyingAsync(userId, token, intentionId);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse GetAllIntentionsBuying(string userId, string token) {
            return base.Channel.GetAllIntentionsBuying(userId, token);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse> GetAllIntentionsBuyingAsync(string userId, string token) {
            return base.Channel.GetAllIntentionsBuyingAsync(userId, token);
        }
        
        public AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse MakeDeal(string userId, string token, int offerId, int requestId, int quantity) {
            return base.Channel.MakeDeal(userId, token, offerId, requestId, quantity);
        }
        
        public System.Threading.Tasks.Task<AgroMarketRD.Playground.AgroMarketWS.IntentionBuyingResponse> MakeDealAsync(string userId, string token, int offerId, int requestId, int quantity) {
            return base.Channel.MakeDealAsync(userId, token, offerId, requestId, quantity);
        }
    }
}
